#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Forecast report:"
  echo "    forecast"
  echo "      generates a textual report of pending and completed tasks in all projects and contexts"
  echo ""
  exit
}

[ "$action" = "forecast" ] && {
     python ~/.todo.actions.d/forecast.py "$TODO_FILE" "$DONE_FILE"
}
